version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - 'dzmitry-varabei'
      - 'andron13'
      - 'SpaNb4'
    commit-message:
      prefix: "chore"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
