version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'dzmitry-varabei'
      - 'andron13'
      - 'SpaNb4'
      - 'Quiddlee'
    commit-message:
      prefix: 'chore'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'dzmitry-varabei'
      - 'andron13'
      - 'SpaNb4'
      - 'Quiddlee'
    commit-message:
      prefix: 'chore'
