import { OG_IMAGE_HEIGHT, OG_IMAGE_WIDTH } from '@/shared/constants';

export const stylesPageTree = {
  container: {
    width: OG_IMAGE_WIDTH,
    height: OG_IMAGE_HEIGHT,
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    alignItems: 'flex-start',
    padding: '100px 80px',
    margin: 0,
    backgroundColor: '#fff',
    fontFamily: 'Inter',
    color: '#000',
    boxSizing: 'border-box',
    position: 'relative',
  },
  mapBg: {
    position: 'absolute',
    top: 0,
    right: 120,
    objectFit: 'contain',
    height: 630,
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 30,
    margin: 0,
  },
  title: {
    fontFamily: 'Inter',
    fontSize: 82,
    fontWeight: 700,
    margin: 0,
  },
  description: {
    fontFamily: 'Inter',
    fontSize: 34,
    fontWeight: 400,
    color: '#000',
    width: '700px',
    margin: 0,
  },
  mascotsContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    position: 'absolute',
    bottom: 45,
    left: 50,
  },
  mascots: {
    objectFit: 'contain',
    width: 430,
  },
  yellowBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '1200px',
    height: '36px',
    backgroundColor: '#ffda1f',
  },
  banner: {
    position: 'absolute',
    top: 60,
    right: 70,
    objectFit: 'contain',
    width: 300,
    height: 300,
  },
} as const;
