import { ROUTES } from '@/core/const';
import { ApiCoursesIds } from '@/entities/course/types';
import { COURSE_TITLES, CourseTitle } from 'data';

export const COURSE_DATE_FORMAT = 'MMM DD, YYYY';
export const MENTORING_DATE_FORMAT = 'MMM, YYYY';

export const API_COURSES_IDS_DICTIONARY: Record<CourseTitle, string> = {
  [COURSE_TITLES.NODE]: '75SiyJCiH4OrIQUKDg0Pci',
  [COURSE_TITLES.AWS_CLOUD_DEVELOPER]: 'L504RMpq3gsKyY0C9EQYI',
  [COURSE_TITLES.AWS_DEVOPS]: '2Za7cDAZ7Bg4o2fRTTsl91',
  [COURSE_TITLES.AWS_FUNDAMENTALS]: '3p8uX8zmCKIVP2FeRzxm5w',
  [COURSE_TITLES.ANGULAR]: '5s34NDFPlgZsDJ259A4dme',
  [COURSE_TITLES.JS_PRESCHOOL_RU]: 'nP9AhZZOnUclChkM0wIsM',
  [COURSE_TITLES.JS_RU]: '45GfCeWyEljTfHzUgnQPod',
  [COURSE_TITLES.REACT]: '22u5y3ir02LMShH6AyNOsE',
  [COURSE_TITLES.JS_EN]: 'EiDyAqKQQpcauf4z8htAb',
};

export const API_COURSES_ROUTES_DICTIONARY: Record<ApiCoursesIds, string> = {
  [API_COURSES_IDS_DICTIONARY['Node.js']]: `/${ROUTES.COURSES}/${ROUTES.NODE_JS}`,
  [API_COURSES_IDS_DICTIONARY['AWS Cloud Developer']]: `/${ROUTES.COURSES}/${ROUTES.AWS_DEVELOPER}`,
  [API_COURSES_IDS_DICTIONARY['AWS DevOps']]: `/${ROUTES.COURSES}/${ROUTES.AWS_DEVOPS}`,
  [API_COURSES_IDS_DICTIONARY['AWS Fundamentals']]: `/${ROUTES.COURSES}/${ROUTES.AWS_FUNDAMENTALS}`,
  [API_COURSES_IDS_DICTIONARY['Angular']]: `/${ROUTES.COURSES}/${ROUTES.ANGULAR}`,
  [API_COURSES_IDS_DICTIONARY['JS / Front-end Pre-school RU']]:
    `/${ROUTES.COURSES}/${ROUTES.JS_PRESCHOOL_RU}`,
  [API_COURSES_IDS_DICTIONARY['JS / Front-end RU']]: `/${ROUTES.COURSES}/${ROUTES.JS_RU}`,
  [API_COURSES_IDS_DICTIONARY['React']]: `/${ROUTES.COURSES}/${ROUTES.REACT}`,
  [API_COURSES_IDS_DICTIONARY['JS / Front-end EN']]: `/${ROUTES.COURSES}/${ROUTES.JS}`,
};
