import { COURSE_TITLES, CourseTitle } from 'data';

export const ALIAS_QUARTER_REGEXP = new RegExp(/-\d{4}(?:-?[Qq][1-4])?/, 'i');
export const COURSE_DATE_FORMAT = 'MMM DD, YYYY';
export const MENTORING_DATE_FORMAT = 'MMM, YYYY';

export const API_COURSES_IDS_DICTIONARY: Record<CourseTitle, string> = {
  [COURSE_TITLES.NODE]: '75SiyJCiH4OrIQUKDg0Pci',
  [COURSE_TITLES.AWS_CLOUD_DEVELOPER]: 'L504RMpq3gsKyY0C9EQYI',
  [COURSE_TITLES.AWS_DEVOPS]: '2Za7cDAZ7Bg4o2fRTTsl91',
  [COURSE_TITLES.AWS_FUNDAMENTALS]: '3p8uX8zmCKIVP2FeRzxm5w',
  [COURSE_TITLES.ANGULAR]: '5s34NDFPlgZsDJ259A4dme',
  [COURSE_TITLES.JS_PRESCHOOL_RU]: 'nP9AhZZOnUclChkM0wIsM',
  [COURSE_TITLES.JS_RU]: '45GfCeWyEljTfHzUgnQPod',
  [COURSE_TITLES.REACT]: '22u5y3ir02LMShH6AyNOsE',
  [COURSE_TITLES.JS_EN]: 'EiDyAqKQQpcauf4z8htAb',
  [COURSE_TITLES.SHORT_TRACK]: 'pb5aNV0EvQpF3EMiSTS7w',
};
