import { ROUTES } from '@/core/const';
import type { Course } from '@/entities/course';
import angular from '@/shared/assets/icons/angular.svg';
import awsBlack from '@/shared/assets/icons/aws-black.svg';
import awsWhite from '@/shared/assets/icons/aws-white.svg';
import html5 from '@/shared/assets/icons/html5.svg';
import javascriptBlack from '@/shared/assets/icons/javascript-black.svg';
import javascript from '@/shared/assets/icons/javascript.svg';
import nodejs from '@/shared/assets/icons/node-js.svg';
import react from '@/shared/assets/icons/react.svg';
import shortTrackIcon from '@/shared/assets/icons/st-icon.svg';
import { COURSE_LINKS, TO_BE_DETERMINED } from '@/shared/constants';
import { COURSE_TITLES } from 'data';

export const courses: Course[] = [
  {
    id: '1',
    title: COURSE_TITLES.JS_PRESCHOOL_RU,
    subTitle: 'Pre-school RU',
    descriptionUrl: COURSE_LINKS.JS_PRESCHOOL_RU,
    altTitle: 'JavaScript / Front-end',
    iconSrc: javascript,
    iconSmall: html5,
    iconFooter: html5,
    secondaryIcon: javascriptBlack,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'ru',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.JS_PRESCHOOL_RU}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#FFFCE9',
      accentColor: '#FFDB20',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '2',
    title: COURSE_TITLES.JS_EN,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.JS_EN,
    altTitle: 'JavaScript / Front-end',
    iconSrc: javascript,
    iconSmall: javascript,
    iconFooter: javascript,
    secondaryIcon: javascriptBlack,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.JS}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#FFFCE9',
      accentColor: '#FFDB20',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '3',
    title: COURSE_TITLES.JS_RU,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.JS_RU,
    altTitle: 'JavaScript / Front-end',
    iconSrc: javascript,
    iconSmall: javascript,
    iconFooter: javascript,
    secondaryIcon: javascriptBlack,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'ru',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.JS_RU}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#FFFCE9',
      accentColor: '#FFDB20',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '4',
    title: COURSE_TITLES.REACT,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.REACT,
    iconSrc: react,
    iconSmall: react,
    iconFooter: react,
    secondaryIcon: react,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.REACT}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#EAF8FE',
      accentColor: '#2BB4EF',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '5',
    title: COURSE_TITLES.ANGULAR,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.ANGULAR,
    iconSrc: angular,
    iconSmall: angular,
    iconFooter: angular,
    secondaryIcon: angular,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.ANGULAR}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#FFEFF2',
      accentColor: '#F95879',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '6',
    title: COURSE_TITLES.NODE,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.NODE,
    iconSrc: nodejs,
    iconSmall: nodejs,
    iconFooter: nodejs,
    secondaryIcon: nodejs,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.NODE_JS}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#F0F9F4',
      accentColor: '#AEDF36',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '7',
    title: COURSE_TITLES.AWS_FUNDAMENTALS,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.AWS_FUNDAMENTALS,
    iconSrc: awsBlack,
    iconSmall: awsBlack,
    iconFooter: awsWhite,
    secondaryIcon: awsBlack,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.AWS_FUNDAMENTALS}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#F4F1FA',
      accentColor: '#7356BF',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },

  {
    id: '8',
    title: COURSE_TITLES.AWS_CLOUD_DEVELOPER,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.AWS_CLOUD_DEVELOPER,
    iconSrc: awsBlack,
    iconSmall: awsBlack,
    secondaryIcon: awsBlack,
    iconFooter: awsWhite,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.AWS_DEVELOPER}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#F4F1FA',
      accentColor: '#7356BF',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '9',
    title: COURSE_TITLES.AWS_DEVOPS,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.AWS_DEVOPS,
    iconSrc: awsBlack,
    iconSmall: awsBlack,
    secondaryIcon: awsBlack,
    iconFooter: awsWhite,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'en',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.AWS_DEVOPS}`,
    enroll: null,
    backgroundStyle: {
      backgroundColor: '#F4F1FA',
      accentColor: '#7356BF',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
  {
    id: '10',
    title: COURSE_TITLES.SHORT_TRACK,
    subTitle: null,
    descriptionUrl: COURSE_LINKS.SHORT_TRACK,
    altTitle: COURSE_TITLES.SHORT_TRACK,
    iconSrc: shortTrackIcon,
    iconSmall: shortTrackIcon,
    iconFooter: shortTrackIcon,
    secondaryIcon: shortTrackIcon,
    startDate: TO_BE_DETERMINED,
    registrationEndDate: TO_BE_DETERMINED,
    language: 'ru',
    mode: 'online',
    detailsUrl: `/${ROUTES.COURSES}/${ROUTES.SHORT_TRACK}`,
    enroll:
      'https://docs.google.com/forms/d/1SKjS03vVS6uxJvlNynGAZZs8spGnoWy1q3rnZUc9pyY/viewform?edit_requested=true',
    backgroundStyle: {
      backgroundColor: '#FFFCE9',
      accentColor: '#FFDB20',
    },
    personalMentoringStartDate: null,
    personalMentoringEndDate: null,
  },
];
