export const SECTION_TYPE = {
  ABOUT_COURSE: 'aboutCourse',
  ABOUT_COURSE_ITEM: 'aboutCourseItem',
  MEDIA_TEXT_BLOCK: 'mediaTextBlock',
  LEARNING_PATH_STAGES: 'learningPathStages',
  HERO: 'heroSection',
  UPCOMING_COURSES: 'upcomingCourses',
  MEDIA_GRID: 'mediaGrid',
  HIGHLIGHT_CARD: 'highlightCard',
  EXTERNAL_EMBED_CONTENT: 'externalEmbedContent',
  INFO_GRID: 'infoGrid',
  MARQUEE: 'marquee',
  SLIDER: 'slider',
  SLIDE: 'slide',
  LINK: 'link',
} as const;
