export const SECTION_TYPE = {
  FEATURE_GRID: 'aboutCourse',
  FEATURE_ITEM: 'aboutCourseItem',
  MEDIA_TEXT_BLOCK: 'mediaTextBlock',
  LEARNING_PATH_STAGE_ITEM: 'learningPathStageItem',
  HERO: 'heroSection',
  MEDIA_GRID: 'mediaGrid',
  HIGHLIGHT_CARD: 'highlightCard',
  EXTERNAL_EMBED_CONTENT: 'externalEmbedContent',
  INFO_GRID: 'infoGrid',
  MARQUEE: 'marquee',
  SLIDER: 'slider',
  SLIDE: 'slide',
  LINK: 'link',
} as const;
