export const stylesCourseTree = {
  container: {
    display: 'flex',
    width: 1200,
    height: 630,
    fontFamily: 'Inter',
  },
  leftSection: {
    flex: 3,
    background: '#000',
    color: '#f0f2f5',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    boxSizing: 'border-box',
    gap: 25,
  },
  rightSection: {
    flex: 2,
    background: '#ffda1f',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 25,
    padding: 20,
    boxSizing: 'border-box',
  },
  logo: {
    width: 250,
    height: 250,
  },
  title: {
    fontSize: 72,
    fontWeight: 700,
    fontFamily: 'Inter',
    margin: 0,
  },
  subtitle: {
    fontSize: 36,
    fontFamily: 'Inter',
    fontWeight: 400,
    margin: 0,
  },
  courseLogo: {
    width: 250,
    height: 250,
    objectFit: 'contain',
  },
  courseTitle: {
    fontSize: 50,
    color: '#000',
    margin: 0,
    fontFamily: 'Inter',
    fontWeight: 400,
    textAlign: 'center',
  },
  startDate: {
    fontSize: 38,
    color: '#000',
    margin: 0,
    fontFamily: 'Inter',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'uppercase',
  },
} as const;
